baseURL = "https://shaninpersonal.xyz"
languageCode = "en-us"
title = "Shanin Website"
theme = "PaperMod"

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = -110
